### ISSUE TITLE
error "DeviceFamily_XYZ undefined

### ISSUE THREAD

**Issue by deepam4ever** [firmwaremodules/Contiki-EOS#1]
I got the below error while compiling. Where should I define DeviceFamily_XYZ?
CC        ecdsa-engines/hw/ecdsa-cc26x2-adapter.c
In file included from ecdsa-engines/hw/ecdsa-cc26x2-adapter.c:41:0:
./ti/devices/DeviceFamily.h:173:6: error: #error "DeviceFamily_XYZ undefined. You must define a DeviceFamily_XYZ!"
ecdsa-engines/hw/ecdsa-cc26x2-adapter.c:42:53: fatal error: ti/devices/DeviceFamily_DIRECTORY/driverlib/pka.h: No such file or directory
compilation terminated.
make: *** [build/native/obj/ecdsa-cc26x2-adapter.o] Error 1

**Comment by firmwareguru** [comment]
Hi @deepam4ever, this project is meant to be dropped into an existing clone of the [Contiki-NG](https://github.com/contiki-ng/contiki-ng) project as an application, e.g. under **examples\eos**.

You would then build this "eos" example app as you would any other Contiki-NG application such as hello-world.

For the TI CC1312r1 target which is what this application was tested on, you would run:

`make TARGET=simplelink BOARD=launchapd/cc1312r1 examples\eos`
